# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80623efad490ab522f41dfbb1e4b4f8918f40723626a7bc23e756d7fff586a0a683ee5fbb1a4691384eb2d14ea64a37dd84db7319aa065d9e4a5e737fa06430a

test:
  secret_key_base: 49ae7f6a37e87ea3ca1320eabf1e62d81097cd4e68d2fa06654503e8f6220a6f2126512844cd7d7a54f949fb6684ae8958899153ac8d263a77fd18e248c24750

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
